---
sidebar: sidebar 
permalink: concept-gfc-enduser-training.html 
keywords: global file cache, training 
summary: 'Vous devez former vos utilisateurs aux bonnes pratiques d"accès aux fichiers partagés via la mise en cache BlueXP Edge.' 
---
= Formation des utilisateurs finaux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez former vos utilisateurs aux bonnes pratiques d'accès aux fichiers partagés via la mise en cache BlueXP Edge.

Il s'agit de la dernière phase du déploiement de la mise en cache BlueXP en périphérie, la phase d'implémentation destinée aux utilisateurs finaux.

Afin de préparer et de rationaliser le processus d'intégration des utilisateurs finaux, utilisez le modèle d'e-mail ci-dessous qui vous aidera à former les utilisateurs finaux sur les moyens de travailler dans un environnement de « données centrales ». Vos utilisateurs pourront ainsi profiter de tous les avantages de la solution de mise en cache BlueXP Edge. Nous avons également publié une vidéo qui peut être partagée à "former" les utilisateurs si nécessaire.

Personnaliser et transférer les ressources suivantes aux utilisateurs finaux pour les préparer au déploiement :

* Vidéo de formation des utilisateurslink:https://www.youtube.com/watch?v=RYvhnTz4bEA["Vidéo de formation des utilisateurs finaux"^]
* Modèle d'e-maillink:https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%20Onboarding%20Email.emltpl["Modèle d'e-mail Mac (.emltpl)"]
+
link:media/Global_File_Cache_Onboarding_Email.msg["Modèle de messagerie Windows (.msg)"]

* Communications d'intégrationlink:https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%20Customer%20Onboarding%20-%20Draft.docx["Document Word (.docx)"]


Reportez-vous au chapitre 14 de la https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guide de l'utilisateur NetApp Global File cache"^] pour du matériel supplémentaire.
