---
sidebar: sidebar 
permalink: fixed-issues.html 
keywords: fixed issues, release notes, fixes, gfc, global file cache 
summary: Consultez les problèmes qui ont été résolus dans la mise en cache BlueXP Edge. 
---
= Résolution des problèmes liés à la mise en cache BlueXP Edge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Consultez les problèmes qui ont été résolus dans la mise en cache BlueXP Edge.



== 1er août 2023 (version 2.3)

* Les corrections suivantes de l'interface utilisateur Optimus Configuration ont été effectuées :
+
** Affiche des informations significatives pour les erreurs au lieu des chaînes d'exception.
** Affiche correctement la date d'expiration de la licence au lieu de n'importe quelle valeur par défaut.
** Affiche correctement les champs nom d'utilisateur/mot de passe lorsque SSL est activé dans l'interface utilisateur.
** Ne répond pas lorsqu'un GFC Core inaccessible est configuré dans l'onglet de configuration Optimus UI Edge.
** Permet de sélectionner plusieurs noms de cache/d'arête dans la liste déroulante Edge.


* Les informations de résumé de licence s'affichent correctement lors de l'affichage des licences expirées et non expirées.
* Correction du redémarrage du service TappN uniquement lorsque la configuration a été correctement mise à jour.
* Ajout d'un bouton d'actualisation dans l'assistant de première utilisation pour afficher le nombre d'arêtes.
* Les informations SSL sont maintenant affichées dans la page de résumé de l'assistant de première utilisation.
* Ajout d'une infrastructure dans Tum pour permettre la configuration des délais d'expiration de minidump et effectuer un minidump correctement.
* Optimus et l'assistant de première utilisation affichent le nombre de licences approprié et une exception lorsque le nombre de licences devient zéro.
* Optimus PSM affiche maintenant un message d'erreur approprié lorsque le nom du serveur Edge saisi est vide.
* Résolution d'un problème lorsque les travaux de pré-remplissage ne sont pas correctement appliqués à plusieurs noms de cache dans Optimus PSM.
* La configuration du Gestionnaire de licences est améliorée pour afficher les erreurs matérielles au lieu des erreurs logicielles.
* L'interface utilisateur d'enregistrement de Zoura affiche une erreur si elle est déjà configurée.
* L'interface utilisateur Optimus et Optimus PSM indiquent maintenant les besoins en processeur et en mémoire de 8 CPU et de 32 Go de RAM respectivement.




== 27 mars 2023 (version 2.2)

* Correction d'un problème de conversion du format horaire de l'exécution d'un travail de pré-remplissage pour l'option « heure de la dernière modification ».
* Résolution d'un problème lié à l'analyse du transfert de fichiers et à sa transmission au service Cloud Insights.
* Edge Sync des fichiers sur tous les abonnés est reconnecté automatiquement lorsqu'il y a une déconnexion avec l'éditeur.
* Exécution de travaux de pré-remplissage fixe sur un Edge si celui-ci est connecté à plusieurs cœurs.
* L'interface utilisateur Optimus affiche désormais la liste Connected Edge sur un éditeur qui participe à la fonctionnalité Edge Sync.




== 24 octobre 2022 (version 2.1)

* Une validation supplémentaire du numéro d'abonnement réseau GFC est effectuée lors de la configuration des licences.
* La prise en charge de Fibre Channel a été ajoutée pour étendre la licence pour une durée spécifique pour les licences basées sur Zuora. Contactez le support Fibre Channel.
* Ajout d'un délai de 15 secondes avant d'écrire un minidump après une collision. Ajout d'un minuteur pour surveiller le minividage et quitter le processus de force si le vidage ne s'effectue pas en 60 secondes. Ces améliorations mineures contribueront à une meilleure analyse.
* Suppression de la propagation des informations de transfert de fichiers individuels vers Cloud Insights, mais ajout de la propagation des informations de résumé de transfert de fichier dans Cloud Insights. La charge sur l'infrastructure convergée est ainsi réduite.
* Ingestion fixe des données et des métadonnées dans Cloud Insights. Cela permet d'utiliser une infrastructure convergée de visualisation des données.
* L'interface utilisateur de Configuration Optimus n'est pas suspendue en cliquant sur le bouton « enregistrement de l'instance à l'EC ».
* Résolution d'un problème où le moniteur Tservice reste manuel pendant la configuration initiale.
* Correction des bogues mineurs dans le service client de l'agent d'infrastructure convergée de réseau réseau réseau de réseau de stockage.




== 25 juillet 2022 (version 2.0)

* Optimus est amélioré en ajoutant des limites aux paramètres de date et d'heure pour la configuration d'ajout de tâches pré-démographiques.
* Optimus PSM affiche maintenant les détails exacts de l'UC dans les détails de pré-demande du système.
* Correction d'une exception dans l'interface utilisateur pendant la configuration de Edge Sync entre la saisie des détails du coordinateur et le clic sur le bouton Actualiser.
* Amélioration de l'interface utilisateur Optimus pour activer/désactiver la fonction Edge Sync sur la périphérie.
* Résolution du problème de plage de dates dans License Server Manager pour l'agrégateur de licences Zuora.
* Correction du PSM Optimus pour afficher les renseignements sur le nombre de locations.
* Logique du serveur de gestion des licences fixes sur le programme de mise à jour de la configuration pendant une mise à niveau.




== 23 juin 2022 (version 1.3.1)

* Lors de la mise à niveau, la version correcte de Microsoft redistribuable n'est pas installée correctement et, par conséquent, Tum ne démarre pas. Le programme d'installation de réseau réseau de stockage a été corrigé pour installer la version redistribuable correcte.
* Le service de gestion des licences réseau (LMS) de réseau de gestion des licences de réseau de réseau de réseau de réseau de gestion des licences de réseau de réseau de réseau de réseau de réseau
* L'interface utilisateur de configuration se lie désormais à la dll System.net.http correcte lors du processus de mise à niveau.




== 19 mai 2022 (version 1.3.0)

* La page de l'interface utilisateur de configuration de la fonctionnalité de synchronisation Edge est mise à jour.
* Correction d'un problème lors de l'ajout de travaux de pré-remplissage pour plusieurs arêtes en même temps via des applets de commande PowerShell.
* Résolution d'un problème d'affichage dans l'interface utilisateur Web de LMS qui affiche l'abonnement NetApp.
* Le script PowerShell de configuration LMS utilise désormais TLS 1.2.
* Correction d'un problème dans TappN (service de préremplissage) et lui permet de continuer à exécuter le travail, malgré des déconnexions transitoires ou des redémarrages de Tum.
* Le service de pré-remplissage TappN est mis à jour pour ignorer les fichiers de récupération si l'espace de cache libre est inférieur à la valeur seuil inférieure.
* Résolution d'un problème dans le service du serveur de gestion des licences (LMS) lors de l'écriture d'un journal de suivi.
* L'infrastructure de consignation pour Tum est mise à jour pour être plus évolutive avec des performances élevées.

