---
settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents relatifs à la mise en cache de BlueXP Edge
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Problèmes résolus
      url: "/fixed-issues.html"
  - title: Commencez
    entries:
    - title: Découvrez la mise en cache BlueXP Edge
      url: "/concept-gfc.html"
    - title: Prérequis pour la mise en cache BlueXP Edge
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Déployez et achetez des licences pour la mise en cache BlueXP Edge
      url: "/task-gfc-getting-started.html"
    - title: Prérequis pour la mise en cache en périphérie BlueXP
      url: "/download-gfc-resources.html"
    - title: Déployez la mise en cache BlueXP Edge
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Utilisez la mise en cache BlueXP Edge
    entries:
    - title: Formation des utilisateurs finaux
      url: "/concept-gfc-enduser-training.html"
    - title: Informations supplémentaires
      url: "/reference-gfc-additional-information.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez la mise en cache BlueXP Edge
      url: concept-gfc.html
    - title: Nouveautés
      url: whats-new.html
    - title: Limites
      url: concept-gfc.html#limitations
  - title: Déployez les composants
    links:
    - title: Déployez Cloud Volumes ONTAP en tant que plateforme de stockage
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: Déployez le serveur et le cœur de gestion de la mise en cache BlueXP
        Edge
      url: task-gfc-getting-started.html#enable-bluexp-edge caching-in-your-working-environment
    - title: Déployez les instances BlueXP Edge Caching
      url: task-deploy-gfc-edge-instances.html
  - title: Former les utilisateurs
    links:
    - title: Formation des utilisateurs finaux
      url: concept-gfc-enduser-training.html
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://bluexp.netapp.com/events
  - title: Autres ressources
    links:
    - title: Utilisations de la mise en cache BlueXP Edge
      url: https://bluexp.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
